In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.linear_model import LogisticRegression

import numpy as np

X=np.array([[1.78],[3.11], [5.45],
[2.44],[2.09],[0.14],[1.72],[1.65],[4.92],[4.37],[4.96],[
2.25],[4.52],[3.69],[5.88],[4.50]])

y = np.array([0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
1])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
y, test_size=0.3,random_state=42)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_proba = model.predict_proba(X_test)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
y, test_size=0.3,random_state=42)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_proba = model.predict_proba(X_test)

accuracy = accuracy_score(y_test, y_pred)

conf_matrix = confusion_matrix(y_test,
y_pred)

class_report = classification_report(y_test,
y_pred)

print("y_pred :: ", y_pred)
print("y_accutaul :: ", y_test)

print("Accuracy : ", accuracy, " \nconf_matrix :: ", conf_matrix, " \nclass_report :: ", class_report)

y_pred ::  [0 0 0 1 1]
y_accutaul ::  [0 1 0 1 1]
Accuracy :  0.8  
conf_matrix ::  [[2 0]
 [1 2]]  
class_report ::                precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.67      0.80         3

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5



In [17]:
from sklearn.datasets import load_iris

from sklearn.linear_model import LogisticRegression
import numpy as np

X, y = load_iris(return_X_y=True)

clf = LogisticRegression(random_state=0, max_iter=1000).fit(X, y)

clf.predict(X[:2, :])

np.array([0, 0])

clf.predict_proba(X[:2, :])

clf.score(X, y)

0.9733333333333334

In [16]:
from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score,confusion_matrix

data = load_iris()

X, y = data.data, data.target 

print(X)

X, y = X[y != 2], y[y != 2]
print("          ---------------------------------------------------               ")
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [19]:
from sklearn.datasets import load_iris

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import KFold, cross_val_score

# Load the Iris dataset

data = load_iris()

X, y = data.data, data.target

model = LogisticRegression(max_iter=200)

# Set up K-Fold Cross-Validation

kf = KFold(n_splits=5, shuffle=True,
random_state=42)

# Perform cross-validation

scores = cross_val_score(model, X, y,
cv=kf, scoring='accuracy')

# Output the results

print(f"Cross-validation scores: {scores}")

print(f"Mean accuracy: {scores.mean():.4f}")

print(f"Standarddev: {scores.std():.4f}")

Cross-validation scores: [1.         1.         0.93333333 0.96666667 0.96666667]
Mean accuracy: 0.9733
Standarddev: 0.0249


In [23]:
import numpy as np

from sklearn.linear_model import LinearRegression

x = [[0, 1], [5, 1], [15, 2], [25, 5],
[35, 11], [45, 15], [55, 34], [60, 35]]

y = [4, 5, 20, 14, 32, 22, 38, 43]

x, y = np.array(x), np.array(y)

model = LinearRegression().fit(x, y)

r_sq = model.score(x, y)

print(model.intercept_)

print(model.coef_)

y_pred = model.predict(x)

print(y_pred)

5.52257927519819
[0.44706965 0.25502548]
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [ ]:
from sklearn import datasets

from sklearn.decomposition import PCA

iris = datasets.load_iris()

X = iris.data

y = iris.target

print('Shape of X,y‘,X.shape,y.shape')

print(iris.feature_names)

target_names = iris.target_names

print('Targets are: ',target_names)

pca = PCA(n_components = 2)

X_r1=pca.fit_transform(X)

print('Explained variance 1st two components',pca.explained_variance_)

print('Explained variance ratio:', pca.explained_variance_ratio_)

print('Singular Values',pca.singular_values_)

Shape of X,y‘,X.shape,y.shape
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Targets are:  ['setosa' 'versicolor' 'virginica']
Explained variance 1st two components [4.22824171 0.24267075]
Explained variance ratio: [0.92461872 0.05306648]
Singular Values [25.09996044  6.01314738]
