In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(5,)


In [7]:
arr.reshape(5,1)
print(arr.shape)

(5,)


In [8]:
arr1 = np.arange(0,10, 3).reshape(4,1)
print(arr1)

[[0]
 [3]
 [6]
 [9]]


In [9]:
#identity matrix
identity =  np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2.itemsize)
print(arr2.dtype)

8
int64


In [11]:
arr3 = np.array([1, 2, 3, 4,5 ])
arr4 = np.array([10, 20, 30, 40, 50 ])
print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]


In [12]:
matrix = np.array([[1,2,3,4,5], [10,20,30,40,50],[100,200,300,400,500]])
print(matrix[0:,2:])

[[  3   4   5]
 [ 30  40  50]
 [300 400 500]]


In [13]:
data = np.array([1,2,3,4,5])
data_mean = data.mean()
data_std = data.std()
print(data.mean())
print(data.std())
normalized_data = (data-data_mean) / data_std
print(normalized_data)




3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
